package jp.co.aisinfo.edu.dao.model;

public class TblZip extends TblZipKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_zip.prefcode
	 * @mbg.generated
	 */
	private String prefcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_zip.citycode
	 * @mbg.generated
	 */
	private Integer citycode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_zip.zip7
	 * @mbg.generated
	 */
	private String zip7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_zip.prefkana
	 * @mbg.generated
	 */
	private String prefkana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_zip.citykana
	 * @mbg.generated
	 */
	private String citykana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_zip.areakana
	 * @mbg.generated
	 */
	private String areakana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_zip.pref
	 * @mbg.generated
	 */
	private String pref;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_zip.city
	 * @mbg.generated
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_zip.area
	 * @mbg.generated
	 */
	private String area;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_zip.prefcode
	 * @return  the value of public.tbl_zip.prefcode
	 * @mbg.generated
	 */
	public String getPrefcode() {
		return prefcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_zip.prefcode
	 * @param prefcode  the value for public.tbl_zip.prefcode
	 * @mbg.generated
	 */
	public void setPrefcode(String prefcode) {
		this.prefcode = prefcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_zip.citycode
	 * @return  the value of public.tbl_zip.citycode
	 * @mbg.generated
	 */
	public Integer getCitycode() {
		return citycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_zip.citycode
	 * @param citycode  the value for public.tbl_zip.citycode
	 * @mbg.generated
	 */
	public void setCitycode(Integer citycode) {
		this.citycode = citycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_zip.zip7
	 * @return  the value of public.tbl_zip.zip7
	 * @mbg.generated
	 */
	public String getZip7() {
		return zip7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_zip.zip7
	 * @param zip7  the value for public.tbl_zip.zip7
	 * @mbg.generated
	 */
	public void setZip7(String zip7) {
		this.zip7 = zip7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_zip.prefkana
	 * @return  the value of public.tbl_zip.prefkana
	 * @mbg.generated
	 */
	public String getPrefkana() {
		return prefkana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_zip.prefkana
	 * @param prefkana  the value for public.tbl_zip.prefkana
	 * @mbg.generated
	 */
	public void setPrefkana(String prefkana) {
		this.prefkana = prefkana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_zip.citykana
	 * @return  the value of public.tbl_zip.citykana
	 * @mbg.generated
	 */
	public String getCitykana() {
		return citykana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_zip.citykana
	 * @param citykana  the value for public.tbl_zip.citykana
	 * @mbg.generated
	 */
	public void setCitykana(String citykana) {
		this.citykana = citykana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_zip.areakana
	 * @return  the value of public.tbl_zip.areakana
	 * @mbg.generated
	 */
	public String getAreakana() {
		return areakana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_zip.areakana
	 * @param areakana  the value for public.tbl_zip.areakana
	 * @mbg.generated
	 */
	public void setAreakana(String areakana) {
		this.areakana = areakana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_zip.pref
	 * @return  the value of public.tbl_zip.pref
	 * @mbg.generated
	 */
	public String getPref() {
		return pref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_zip.pref
	 * @param pref  the value for public.tbl_zip.pref
	 * @mbg.generated
	 */
	public void setPref(String pref) {
		this.pref = pref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_zip.city
	 * @return  the value of public.tbl_zip.city
	 * @mbg.generated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_zip.city
	 * @param city  the value for public.tbl_zip.city
	 * @mbg.generated
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_zip.area
	 * @return  the value of public.tbl_zip.area
	 * @mbg.generated
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_zip.area
	 * @param area  the value for public.tbl_zip.area
	 * @mbg.generated
	 */
	public void setArea(String area) {
		this.area = area;
	}
}