package jp.co.aisinfo.edu.dao.model;

import java.util.ArrayList;
import java.util.List;

public class TblZipExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    public TblZipExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZipSeqIsNull() {
            addCriterion("zip_seq is null");
            return (Criteria) this;
        }

        public Criteria andZipSeqIsNotNull() {
            addCriterion("zip_seq is not null");
            return (Criteria) this;
        }

        public Criteria andZipSeqEqualTo(Integer value) {
            addCriterion("zip_seq =", value, "zipSeq");
            return (Criteria) this;
        }

        public Criteria andZipSeqNotEqualTo(Integer value) {
            addCriterion("zip_seq <>", value, "zipSeq");
            return (Criteria) this;
        }

        public Criteria andZipSeqGreaterThan(Integer value) {
            addCriterion("zip_seq >", value, "zipSeq");
            return (Criteria) this;
        }

        public Criteria andZipSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("zip_seq >=", value, "zipSeq");
            return (Criteria) this;
        }

        public Criteria andZipSeqLessThan(Integer value) {
            addCriterion("zip_seq <", value, "zipSeq");
            return (Criteria) this;
        }

        public Criteria andZipSeqLessThanOrEqualTo(Integer value) {
            addCriterion("zip_seq <=", value, "zipSeq");
            return (Criteria) this;
        }

        public Criteria andZipSeqIn(List<Integer> values) {
            addCriterion("zip_seq in", values, "zipSeq");
            return (Criteria) this;
        }

        public Criteria andZipSeqNotIn(List<Integer> values) {
            addCriterion("zip_seq not in", values, "zipSeq");
            return (Criteria) this;
        }

        public Criteria andZipSeqBetween(Integer value1, Integer value2) {
            addCriterion("zip_seq between", value1, value2, "zipSeq");
            return (Criteria) this;
        }

        public Criteria andZipSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("zip_seq not between", value1, value2, "zipSeq");
            return (Criteria) this;
        }

        public Criteria andPrefcodeIsNull() {
            addCriterion("prefcode is null");
            return (Criteria) this;
        }

        public Criteria andPrefcodeIsNotNull() {
            addCriterion("prefcode is not null");
            return (Criteria) this;
        }

        public Criteria andPrefcodeEqualTo(Integer value) {
            addCriterion("prefcode =", value, "prefcode");
            return (Criteria) this;
        }

        public Criteria andPrefcodeNotEqualTo(Integer value) {
            addCriterion("prefcode <>", value, "prefcode");
            return (Criteria) this;
        }

        public Criteria andPrefcodeGreaterThan(Integer value) {
            addCriterion("prefcode >", value, "prefcode");
            return (Criteria) this;
        }

        public Criteria andPrefcodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("prefcode >=", value, "prefcode");
            return (Criteria) this;
        }

        public Criteria andPrefcodeLessThan(Integer value) {
            addCriterion("prefcode <", value, "prefcode");
            return (Criteria) this;
        }

        public Criteria andPrefcodeLessThanOrEqualTo(Integer value) {
            addCriterion("prefcode <=", value, "prefcode");
            return (Criteria) this;
        }

        public Criteria andPrefcodeIn(List<Integer> values) {
            addCriterion("prefcode in", values, "prefcode");
            return (Criteria) this;
        }

        public Criteria andPrefcodeNotIn(List<Integer> values) {
            addCriterion("prefcode not in", values, "prefcode");
            return (Criteria) this;
        }

        public Criteria andPrefcodeBetween(Integer value1, Integer value2) {
            addCriterion("prefcode between", value1, value2, "prefcode");
            return (Criteria) this;
        }

        public Criteria andPrefcodeNotBetween(Integer value1, Integer value2) {
            addCriterion("prefcode not between", value1, value2, "prefcode");
            return (Criteria) this;
        }

        public Criteria andCitycodeIsNull() {
            addCriterion("citycode is null");
            return (Criteria) this;
        }

        public Criteria andCitycodeIsNotNull() {
            addCriterion("citycode is not null");
            return (Criteria) this;
        }

        public Criteria andCitycodeEqualTo(Integer value) {
            addCriterion("citycode =", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotEqualTo(Integer value) {
            addCriterion("citycode <>", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeGreaterThan(Integer value) {
            addCriterion("citycode >", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("citycode >=", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeLessThan(Integer value) {
            addCriterion("citycode <", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeLessThanOrEqualTo(Integer value) {
            addCriterion("citycode <=", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeIn(List<Integer> values) {
            addCriterion("citycode in", values, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotIn(List<Integer> values) {
            addCriterion("citycode not in", values, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeBetween(Integer value1, Integer value2) {
            addCriterion("citycode between", value1, value2, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotBetween(Integer value1, Integer value2) {
            addCriterion("citycode not between", value1, value2, "citycode");
            return (Criteria) this;
        }

        public Criteria andZip7IsNull() {
            addCriterion("zip7 is null");
            return (Criteria) this;
        }

        public Criteria andZip7IsNotNull() {
            addCriterion("zip7 is not null");
            return (Criteria) this;
        }

        public Criteria andZip7EqualTo(String value) {
            addCriterion("zip7 =", value, "zip7");
            return (Criteria) this;
        }

        public Criteria andZip7NotEqualTo(String value) {
            addCriterion("zip7 <>", value, "zip7");
            return (Criteria) this;
        }

        public Criteria andZip7GreaterThan(String value) {
            addCriterion("zip7 >", value, "zip7");
            return (Criteria) this;
        }

        public Criteria andZip7GreaterThanOrEqualTo(String value) {
            addCriterion("zip7 >=", value, "zip7");
            return (Criteria) this;
        }

        public Criteria andZip7LessThan(String value) {
            addCriterion("zip7 <", value, "zip7");
            return (Criteria) this;
        }

        public Criteria andZip7LessThanOrEqualTo(String value) {
            addCriterion("zip7 <=", value, "zip7");
            return (Criteria) this;
        }

        public Criteria andZip7Like(String value) {
            addCriterion("zip7 like", value, "zip7");
            return (Criteria) this;
        }

        public Criteria andZip7NotLike(String value) {
            addCriterion("zip7 not like", value, "zip7");
            return (Criteria) this;
        }

        public Criteria andZip7In(List<String> values) {
            addCriterion("zip7 in", values, "zip7");
            return (Criteria) this;
        }

        public Criteria andZip7NotIn(List<String> values) {
            addCriterion("zip7 not in", values, "zip7");
            return (Criteria) this;
        }

        public Criteria andZip7Between(String value1, String value2) {
            addCriterion("zip7 between", value1, value2, "zip7");
            return (Criteria) this;
        }

        public Criteria andZip7NotBetween(String value1, String value2) {
            addCriterion("zip7 not between", value1, value2, "zip7");
            return (Criteria) this;
        }

        public Criteria andPrefkanaIsNull() {
            addCriterion("prefkana is null");
            return (Criteria) this;
        }

        public Criteria andPrefkanaIsNotNull() {
            addCriterion("prefkana is not null");
            return (Criteria) this;
        }

        public Criteria andPrefkanaEqualTo(String value) {
            addCriterion("prefkana =", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaNotEqualTo(String value) {
            addCriterion("prefkana <>", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaGreaterThan(String value) {
            addCriterion("prefkana >", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaGreaterThanOrEqualTo(String value) {
            addCriterion("prefkana >=", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaLessThan(String value) {
            addCriterion("prefkana <", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaLessThanOrEqualTo(String value) {
            addCriterion("prefkana <=", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaLike(String value) {
            addCriterion("prefkana like", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaNotLike(String value) {
            addCriterion("prefkana not like", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaIn(List<String> values) {
            addCriterion("prefkana in", values, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaNotIn(List<String> values) {
            addCriterion("prefkana not in", values, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaBetween(String value1, String value2) {
            addCriterion("prefkana between", value1, value2, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaNotBetween(String value1, String value2) {
            addCriterion("prefkana not between", value1, value2, "prefkana");
            return (Criteria) this;
        }

        public Criteria andCitykanaIsNull() {
            addCriterion("citykana is null");
            return (Criteria) this;
        }

        public Criteria andCitykanaIsNotNull() {
            addCriterion("citykana is not null");
            return (Criteria) this;
        }

        public Criteria andCitykanaEqualTo(String value) {
            addCriterion("citykana =", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaNotEqualTo(String value) {
            addCriterion("citykana <>", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaGreaterThan(String value) {
            addCriterion("citykana >", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaGreaterThanOrEqualTo(String value) {
            addCriterion("citykana >=", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaLessThan(String value) {
            addCriterion("citykana <", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaLessThanOrEqualTo(String value) {
            addCriterion("citykana <=", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaLike(String value) {
            addCriterion("citykana like", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaNotLike(String value) {
            addCriterion("citykana not like", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaIn(List<String> values) {
            addCriterion("citykana in", values, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaNotIn(List<String> values) {
            addCriterion("citykana not in", values, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaBetween(String value1, String value2) {
            addCriterion("citykana between", value1, value2, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaNotBetween(String value1, String value2) {
            addCriterion("citykana not between", value1, value2, "citykana");
            return (Criteria) this;
        }

        public Criteria andAreakanaIsNull() {
            addCriterion("areakana is null");
            return (Criteria) this;
        }

        public Criteria andAreakanaIsNotNull() {
            addCriterion("areakana is not null");
            return (Criteria) this;
        }

        public Criteria andAreakanaEqualTo(String value) {
            addCriterion("areakana =", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaNotEqualTo(String value) {
            addCriterion("areakana <>", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaGreaterThan(String value) {
            addCriterion("areakana >", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaGreaterThanOrEqualTo(String value) {
            addCriterion("areakana >=", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaLessThan(String value) {
            addCriterion("areakana <", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaLessThanOrEqualTo(String value) {
            addCriterion("areakana <=", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaLike(String value) {
            addCriterion("areakana like", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaNotLike(String value) {
            addCriterion("areakana not like", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaIn(List<String> values) {
            addCriterion("areakana in", values, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaNotIn(List<String> values) {
            addCriterion("areakana not in", values, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaBetween(String value1, String value2) {
            addCriterion("areakana between", value1, value2, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaNotBetween(String value1, String value2) {
            addCriterion("areakana not between", value1, value2, "areakana");
            return (Criteria) this;
        }

        public Criteria andPrefIsNull() {
            addCriterion("pref is null");
            return (Criteria) this;
        }

        public Criteria andPrefIsNotNull() {
            addCriterion("pref is not null");
            return (Criteria) this;
        }

        public Criteria andPrefEqualTo(String value) {
            addCriterion("pref =", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotEqualTo(String value) {
            addCriterion("pref <>", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefGreaterThan(String value) {
            addCriterion("pref >", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefGreaterThanOrEqualTo(String value) {
            addCriterion("pref >=", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefLessThan(String value) {
            addCriterion("pref <", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefLessThanOrEqualTo(String value) {
            addCriterion("pref <=", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefLike(String value) {
            addCriterion("pref like", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotLike(String value) {
            addCriterion("pref not like", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefIn(List<String> values) {
            addCriterion("pref in", values, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotIn(List<String> values) {
            addCriterion("pref not in", values, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefBetween(String value1, String value2) {
            addCriterion("pref between", value1, value2, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotBetween(String value1, String value2) {
            addCriterion("pref not between", value1, value2, "pref");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tbl_zip
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}