package jp.co.aisinfo.edu.dao.model;

public class TblZipKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_zip.zip_seq
	 * @mbg.generated
	 */
	private Integer zipSeq;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_zip.zip_seq
	 * @return  the value of public.tbl_zip.zip_seq
	 * @mbg.generated
	 */
	public Integer getZipSeq() {
		return zipSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_zip.zip_seq
	 * @param zipSeq  the value for public.tbl_zip.zip_seq
	 * @mbg.generated
	 */
	public void setZipSeq(Integer zipSeq) {
		this.zipSeq = zipSeq;
	}
}