package jp.co.aisinfo.edu.dao.model;

import java.util.ArrayList;
import java.util.List;

public class TmpZipcodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    public TmpZipcodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZipoldIsNull() {
            addCriterion("zipold is null");
            return (Criteria) this;
        }

        public Criteria andZipoldIsNotNull() {
            addCriterion("zipold is not null");
            return (Criteria) this;
        }

        public Criteria andZipoldEqualTo(String value) {
            addCriterion("zipold =", value, "zipold");
            return (Criteria) this;
        }

        public Criteria andZipoldNotEqualTo(String value) {
            addCriterion("zipold <>", value, "zipold");
            return (Criteria) this;
        }

        public Criteria andZipoldGreaterThan(String value) {
            addCriterion("zipold >", value, "zipold");
            return (Criteria) this;
        }

        public Criteria andZipoldGreaterThanOrEqualTo(String value) {
            addCriterion("zipold >=", value, "zipold");
            return (Criteria) this;
        }

        public Criteria andZipoldLessThan(String value) {
            addCriterion("zipold <", value, "zipold");
            return (Criteria) this;
        }

        public Criteria andZipoldLessThanOrEqualTo(String value) {
            addCriterion("zipold <=", value, "zipold");
            return (Criteria) this;
        }

        public Criteria andZipoldLike(String value) {
            addCriterion("zipold like", value, "zipold");
            return (Criteria) this;
        }

        public Criteria andZipoldNotLike(String value) {
            addCriterion("zipold not like", value, "zipold");
            return (Criteria) this;
        }

        public Criteria andZipoldIn(List<String> values) {
            addCriterion("zipold in", values, "zipold");
            return (Criteria) this;
        }

        public Criteria andZipoldNotIn(List<String> values) {
            addCriterion("zipold not in", values, "zipold");
            return (Criteria) this;
        }

        public Criteria andZipoldBetween(String value1, String value2) {
            addCriterion("zipold between", value1, value2, "zipold");
            return (Criteria) this;
        }

        public Criteria andZipoldNotBetween(String value1, String value2) {
            addCriterion("zipold not between", value1, value2, "zipold");
            return (Criteria) this;
        }

        public Criteria andPrefkanaIsNull() {
            addCriterion("prefkana is null");
            return (Criteria) this;
        }

        public Criteria andPrefkanaIsNotNull() {
            addCriterion("prefkana is not null");
            return (Criteria) this;
        }

        public Criteria andPrefkanaEqualTo(String value) {
            addCriterion("prefkana =", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaNotEqualTo(String value) {
            addCriterion("prefkana <>", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaGreaterThan(String value) {
            addCriterion("prefkana >", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaGreaterThanOrEqualTo(String value) {
            addCriterion("prefkana >=", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaLessThan(String value) {
            addCriterion("prefkana <", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaLessThanOrEqualTo(String value) {
            addCriterion("prefkana <=", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaLike(String value) {
            addCriterion("prefkana like", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaNotLike(String value) {
            addCriterion("prefkana not like", value, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaIn(List<String> values) {
            addCriterion("prefkana in", values, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaNotIn(List<String> values) {
            addCriterion("prefkana not in", values, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaBetween(String value1, String value2) {
            addCriterion("prefkana between", value1, value2, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefkanaNotBetween(String value1, String value2) {
            addCriterion("prefkana not between", value1, value2, "prefkana");
            return (Criteria) this;
        }

        public Criteria andPrefIsNull() {
            addCriterion("pref is null");
            return (Criteria) this;
        }

        public Criteria andPrefIsNotNull() {
            addCriterion("pref is not null");
            return (Criteria) this;
        }

        public Criteria andPrefEqualTo(String value) {
            addCriterion("pref =", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotEqualTo(String value) {
            addCriterion("pref <>", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefGreaterThan(String value) {
            addCriterion("pref >", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefGreaterThanOrEqualTo(String value) {
            addCriterion("pref >=", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefLessThan(String value) {
            addCriterion("pref <", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefLessThanOrEqualTo(String value) {
            addCriterion("pref <=", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefLike(String value) {
            addCriterion("pref like", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotLike(String value) {
            addCriterion("pref not like", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefIn(List<String> values) {
            addCriterion("pref in", values, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotIn(List<String> values) {
            addCriterion("pref not in", values, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefBetween(String value1, String value2) {
            addCriterion("pref between", value1, value2, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotBetween(String value1, String value2) {
            addCriterion("pref not between", value1, value2, "pref");
            return (Criteria) this;
        }

        public Criteria andJiscodeIsNull() {
            addCriterion("jiscode is null");
            return (Criteria) this;
        }

        public Criteria andJiscodeIsNotNull() {
            addCriterion("jiscode is not null");
            return (Criteria) this;
        }

        public Criteria andJiscodeEqualTo(String value) {
            addCriterion("jiscode =", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeNotEqualTo(String value) {
            addCriterion("jiscode <>", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeGreaterThan(String value) {
            addCriterion("jiscode >", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeGreaterThanOrEqualTo(String value) {
            addCriterion("jiscode >=", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeLessThan(String value) {
            addCriterion("jiscode <", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeLessThanOrEqualTo(String value) {
            addCriterion("jiscode <=", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeLike(String value) {
            addCriterion("jiscode like", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeNotLike(String value) {
            addCriterion("jiscode not like", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeIn(List<String> values) {
            addCriterion("jiscode in", values, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeNotIn(List<String> values) {
            addCriterion("jiscode not in", values, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeBetween(String value1, String value2) {
            addCriterion("jiscode between", value1, value2, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeNotBetween(String value1, String value2) {
            addCriterion("jiscode not between", value1, value2, "jiscode");
            return (Criteria) this;
        }

        public Criteria andFlag5IsNull() {
            addCriterion("flag5 is null");
            return (Criteria) this;
        }

        public Criteria andFlag5IsNotNull() {
            addCriterion("flag5 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag5EqualTo(Short value) {
            addCriterion("flag5 =", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotEqualTo(Short value) {
            addCriterion("flag5 <>", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5GreaterThan(Short value) {
            addCriterion("flag5 >", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5GreaterThanOrEqualTo(Short value) {
            addCriterion("flag5 >=", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5LessThan(Short value) {
            addCriterion("flag5 <", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5LessThanOrEqualTo(Short value) {
            addCriterion("flag5 <=", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5In(List<Short> values) {
            addCriterion("flag5 in", values, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotIn(List<Short> values) {
            addCriterion("flag5 not in", values, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5Between(Short value1, Short value2) {
            addCriterion("flag5 between", value1, value2, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotBetween(Short value1, Short value2) {
            addCriterion("flag5 not between", value1, value2, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag4IsNull() {
            addCriterion("flag4 is null");
            return (Criteria) this;
        }

        public Criteria andFlag4IsNotNull() {
            addCriterion("flag4 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag4EqualTo(Short value) {
            addCriterion("flag4 =", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotEqualTo(Short value) {
            addCriterion("flag4 <>", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4GreaterThan(Short value) {
            addCriterion("flag4 >", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4GreaterThanOrEqualTo(Short value) {
            addCriterion("flag4 >=", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4LessThan(Short value) {
            addCriterion("flag4 <", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4LessThanOrEqualTo(Short value) {
            addCriterion("flag4 <=", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4In(List<Short> values) {
            addCriterion("flag4 in", values, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotIn(List<Short> values) {
            addCriterion("flag4 not in", values, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4Between(Short value1, Short value2) {
            addCriterion("flag4 between", value1, value2, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotBetween(Short value1, Short value2) {
            addCriterion("flag4 not between", value1, value2, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag3IsNull() {
            addCriterion("flag3 is null");
            return (Criteria) this;
        }

        public Criteria andFlag3IsNotNull() {
            addCriterion("flag3 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag3EqualTo(Short value) {
            addCriterion("flag3 =", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotEqualTo(Short value) {
            addCriterion("flag3 <>", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3GreaterThan(Short value) {
            addCriterion("flag3 >", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3GreaterThanOrEqualTo(Short value) {
            addCriterion("flag3 >=", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3LessThan(Short value) {
            addCriterion("flag3 <", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3LessThanOrEqualTo(Short value) {
            addCriterion("flag3 <=", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3In(List<Short> values) {
            addCriterion("flag3 in", values, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotIn(List<Short> values) {
            addCriterion("flag3 not in", values, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3Between(Short value1, Short value2) {
            addCriterion("flag3 between", value1, value2, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotBetween(Short value1, Short value2) {
            addCriterion("flag3 not between", value1, value2, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag2IsNull() {
            addCriterion("flag2 is null");
            return (Criteria) this;
        }

        public Criteria andFlag2IsNotNull() {
            addCriterion("flag2 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag2EqualTo(Short value) {
            addCriterion("flag2 =", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotEqualTo(Short value) {
            addCriterion("flag2 <>", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2GreaterThan(Short value) {
            addCriterion("flag2 >", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2GreaterThanOrEqualTo(Short value) {
            addCriterion("flag2 >=", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2LessThan(Short value) {
            addCriterion("flag2 <", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2LessThanOrEqualTo(Short value) {
            addCriterion("flag2 <=", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2In(List<Short> values) {
            addCriterion("flag2 in", values, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotIn(List<Short> values) {
            addCriterion("flag2 not in", values, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2Between(Short value1, Short value2) {
            addCriterion("flag2 between", value1, value2, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotBetween(Short value1, Short value2) {
            addCriterion("flag2 not between", value1, value2, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag1IsNull() {
            addCriterion("flag1 is null");
            return (Criteria) this;
        }

        public Criteria andFlag1IsNotNull() {
            addCriterion("flag1 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag1EqualTo(Short value) {
            addCriterion("flag1 =", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotEqualTo(Short value) {
            addCriterion("flag1 <>", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1GreaterThan(Short value) {
            addCriterion("flag1 >", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1GreaterThanOrEqualTo(Short value) {
            addCriterion("flag1 >=", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1LessThan(Short value) {
            addCriterion("flag1 <", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1LessThanOrEqualTo(Short value) {
            addCriterion("flag1 <=", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1In(List<Short> values) {
            addCriterion("flag1 in", values, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotIn(List<Short> values) {
            addCriterion("flag1 not in", values, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1Between(Short value1, Short value2) {
            addCriterion("flag1 between", value1, value2, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotBetween(Short value1, Short value2) {
            addCriterion("flag1 not between", value1, value2, "flag1");
            return (Criteria) this;
        }

        public Criteria andCitykanaIsNull() {
            addCriterion("citykana is null");
            return (Criteria) this;
        }

        public Criteria andCitykanaIsNotNull() {
            addCriterion("citykana is not null");
            return (Criteria) this;
        }

        public Criteria andCitykanaEqualTo(String value) {
            addCriterion("citykana =", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaNotEqualTo(String value) {
            addCriterion("citykana <>", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaGreaterThan(String value) {
            addCriterion("citykana >", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaGreaterThanOrEqualTo(String value) {
            addCriterion("citykana >=", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaLessThan(String value) {
            addCriterion("citykana <", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaLessThanOrEqualTo(String value) {
            addCriterion("citykana <=", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaLike(String value) {
            addCriterion("citykana like", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaNotLike(String value) {
            addCriterion("citykana not like", value, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaIn(List<String> values) {
            addCriterion("citykana in", values, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaNotIn(List<String> values) {
            addCriterion("citykana not in", values, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaBetween(String value1, String value2) {
            addCriterion("citykana between", value1, value2, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitykanaNotBetween(String value1, String value2) {
            addCriterion("citykana not between", value1, value2, "citykana");
            return (Criteria) this;
        }

        public Criteria andCitycodeIsNull() {
            addCriterion("citycode is null");
            return (Criteria) this;
        }

        public Criteria andCitycodeIsNotNull() {
            addCriterion("citycode is not null");
            return (Criteria) this;
        }

        public Criteria andCitycodeEqualTo(String value) {
            addCriterion("citycode =", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotEqualTo(String value) {
            addCriterion("citycode <>", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeGreaterThan(String value) {
            addCriterion("citycode >", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeGreaterThanOrEqualTo(String value) {
            addCriterion("citycode >=", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeLessThan(String value) {
            addCriterion("citycode <", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeLessThanOrEqualTo(String value) {
            addCriterion("citycode <=", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeLike(String value) {
            addCriterion("citycode like", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotLike(String value) {
            addCriterion("citycode not like", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeIn(List<String> values) {
            addCriterion("citycode in", values, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotIn(List<String> values) {
            addCriterion("citycode not in", values, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeBetween(String value1, String value2) {
            addCriterion("citycode between", value1, value2, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotBetween(String value1, String value2) {
            addCriterion("citycode not between", value1, value2, "citycode");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andAreakanaIsNull() {
            addCriterion("areakana is null");
            return (Criteria) this;
        }

        public Criteria andAreakanaIsNotNull() {
            addCriterion("areakana is not null");
            return (Criteria) this;
        }

        public Criteria andAreakanaEqualTo(String value) {
            addCriterion("areakana =", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaNotEqualTo(String value) {
            addCriterion("areakana <>", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaGreaterThan(String value) {
            addCriterion("areakana >", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaGreaterThanOrEqualTo(String value) {
            addCriterion("areakana >=", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaLessThan(String value) {
            addCriterion("areakana <", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaLessThanOrEqualTo(String value) {
            addCriterion("areakana <=", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaLike(String value) {
            addCriterion("areakana like", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaNotLike(String value) {
            addCriterion("areakana not like", value, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaIn(List<String> values) {
            addCriterion("areakana in", values, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaNotIn(List<String> values) {
            addCriterion("areakana not in", values, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaBetween(String value1, String value2) {
            addCriterion("areakana between", value1, value2, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreakanaNotBetween(String value1, String value2) {
            addCriterion("areakana not between", value1, value2, "areakana");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andFlag6IsNull() {
            addCriterion("flag6 is null");
            return (Criteria) this;
        }

        public Criteria andFlag6IsNotNull() {
            addCriterion("flag6 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag6EqualTo(Short value) {
            addCriterion("flag6 =", value, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6NotEqualTo(Short value) {
            addCriterion("flag6 <>", value, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6GreaterThan(Short value) {
            addCriterion("flag6 >", value, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6GreaterThanOrEqualTo(Short value) {
            addCriterion("flag6 >=", value, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6LessThan(Short value) {
            addCriterion("flag6 <", value, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6LessThanOrEqualTo(Short value) {
            addCriterion("flag6 <=", value, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6In(List<Short> values) {
            addCriterion("flag6 in", values, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6NotIn(List<Short> values) {
            addCriterion("flag6 not in", values, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6Between(Short value1, Short value2) {
            addCriterion("flag6 between", value1, value2, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6NotBetween(Short value1, Short value2) {
            addCriterion("flag6 not between", value1, value2, "flag6");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}