package jp.co.aisinfo.edu.dao.model;

public class TmpZipcode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.zipold
	 * @mbg.generated
	 */
	private String zipold;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.prefkana
	 * @mbg.generated
	 */
	private String prefkana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.pref
	 * @mbg.generated
	 */
	private String pref;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.jiscode
	 * @mbg.generated
	 */
	private String jiscode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.flag5
	 * @mbg.generated
	 */
	private Short flag5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.flag4
	 * @mbg.generated
	 */
	private Short flag4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.flag3
	 * @mbg.generated
	 */
	private Short flag3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.flag2
	 * @mbg.generated
	 */
	private Short flag2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.flag1
	 * @mbg.generated
	 */
	private Short flag1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.citykana
	 * @mbg.generated
	 */
	private String citykana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.citycode
	 * @mbg.generated
	 */
	private String citycode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.city
	 * @mbg.generated
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.areakana
	 * @mbg.generated
	 */
	private String areakana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.area
	 * @mbg.generated
	 */
	private String area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tmp_zipcode.flag6
	 * @mbg.generated
	 */
	private Short flag6;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.zipold
	 * @return  the value of public.tmp_zipcode.zipold
	 * @mbg.generated
	 */
	public String getZipold() {
		return zipold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.zipold
	 * @param zipold  the value for public.tmp_zipcode.zipold
	 * @mbg.generated
	 */
	public void setZipold(String zipold) {
		this.zipold = zipold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.prefkana
	 * @return  the value of public.tmp_zipcode.prefkana
	 * @mbg.generated
	 */
	public String getPrefkana() {
		return prefkana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.prefkana
	 * @param prefkana  the value for public.tmp_zipcode.prefkana
	 * @mbg.generated
	 */
	public void setPrefkana(String prefkana) {
		this.prefkana = prefkana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.pref
	 * @return  the value of public.tmp_zipcode.pref
	 * @mbg.generated
	 */
	public String getPref() {
		return pref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.pref
	 * @param pref  the value for public.tmp_zipcode.pref
	 * @mbg.generated
	 */
	public void setPref(String pref) {
		this.pref = pref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.jiscode
	 * @return  the value of public.tmp_zipcode.jiscode
	 * @mbg.generated
	 */
	public String getJiscode() {
		return jiscode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.jiscode
	 * @param jiscode  the value for public.tmp_zipcode.jiscode
	 * @mbg.generated
	 */
	public void setJiscode(String jiscode) {
		this.jiscode = jiscode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.flag5
	 * @return  the value of public.tmp_zipcode.flag5
	 * @mbg.generated
	 */
	public Short getFlag5() {
		return flag5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.flag5
	 * @param flag5  the value for public.tmp_zipcode.flag5
	 * @mbg.generated
	 */
	public void setFlag5(Short flag5) {
		this.flag5 = flag5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.flag4
	 * @return  the value of public.tmp_zipcode.flag4
	 * @mbg.generated
	 */
	public Short getFlag4() {
		return flag4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.flag4
	 * @param flag4  the value for public.tmp_zipcode.flag4
	 * @mbg.generated
	 */
	public void setFlag4(Short flag4) {
		this.flag4 = flag4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.flag3
	 * @return  the value of public.tmp_zipcode.flag3
	 * @mbg.generated
	 */
	public Short getFlag3() {
		return flag3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.flag3
	 * @param flag3  the value for public.tmp_zipcode.flag3
	 * @mbg.generated
	 */
	public void setFlag3(Short flag3) {
		this.flag3 = flag3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.flag2
	 * @return  the value of public.tmp_zipcode.flag2
	 * @mbg.generated
	 */
	public Short getFlag2() {
		return flag2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.flag2
	 * @param flag2  the value for public.tmp_zipcode.flag2
	 * @mbg.generated
	 */
	public void setFlag2(Short flag2) {
		this.flag2 = flag2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.flag1
	 * @return  the value of public.tmp_zipcode.flag1
	 * @mbg.generated
	 */
	public Short getFlag1() {
		return flag1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.flag1
	 * @param flag1  the value for public.tmp_zipcode.flag1
	 * @mbg.generated
	 */
	public void setFlag1(Short flag1) {
		this.flag1 = flag1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.citykana
	 * @return  the value of public.tmp_zipcode.citykana
	 * @mbg.generated
	 */
	public String getCitykana() {
		return citykana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.citykana
	 * @param citykana  the value for public.tmp_zipcode.citykana
	 * @mbg.generated
	 */
	public void setCitykana(String citykana) {
		this.citykana = citykana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.citycode
	 * @return  the value of public.tmp_zipcode.citycode
	 * @mbg.generated
	 */
	public String getCitycode() {
		return citycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.citycode
	 * @param citycode  the value for public.tmp_zipcode.citycode
	 * @mbg.generated
	 */
	public void setCitycode(String citycode) {
		this.citycode = citycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.city
	 * @return  the value of public.tmp_zipcode.city
	 * @mbg.generated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.city
	 * @param city  the value for public.tmp_zipcode.city
	 * @mbg.generated
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.areakana
	 * @return  the value of public.tmp_zipcode.areakana
	 * @mbg.generated
	 */
	public String getAreakana() {
		return areakana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.areakana
	 * @param areakana  the value for public.tmp_zipcode.areakana
	 * @mbg.generated
	 */
	public void setAreakana(String areakana) {
		this.areakana = areakana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.area
	 * @return  the value of public.tmp_zipcode.area
	 * @mbg.generated
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.area
	 * @param area  the value for public.tmp_zipcode.area
	 * @mbg.generated
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tmp_zipcode.flag6
	 * @return  the value of public.tmp_zipcode.flag6
	 * @mbg.generated
	 */
	public Short getFlag6() {
		return flag6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tmp_zipcode.flag6
	 * @param flag6  the value for public.tmp_zipcode.flag6
	 * @mbg.generated
	 */
	public void setFlag6(Short flag6) {
		this.flag6 = flag6;
	}
}