package jp.co.aisinfo.edu.dao.client;

import java.util.List;
import jp.co.aisinfo.edu.dao.model.TblZip;
import jp.co.aisinfo.edu.dao.model.TblZipExample;
import jp.co.aisinfo.edu.dao.model.TblZipKey;
import org.apache.ibatis.annotations.Param;

public interface TblZipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    long countByExample(TblZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    int deleteByExample(TblZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TblZipKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    int insert(TblZip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    int insertSelective(TblZip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    List<TblZip> selectByExample(TblZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    TblZip selectByPrimaryKey(TblZipKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TblZip record, @Param("example") TblZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TblZip record, @Param("example") TblZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TblZip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tbl_zip
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TblZip record);
}