package jp.co.aisinfo.edu.dao.client;

import java.util.List;
import jp.co.aisinfo.edu.dao.model.TmpZipcode;
import jp.co.aisinfo.edu.dao.model.TmpZipcodeExample;
import org.apache.ibatis.annotations.Param;

public interface TmpZipcodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    long countByExample(TmpZipcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    int deleteByExample(TmpZipcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    int insert(TmpZipcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    int insertSelective(TmpZipcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    List<TmpZipcode> selectByExample(TmpZipcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TmpZipcode record, @Param("example") TmpZipcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tmp_zipcode
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TmpZipcode record, @Param("example") TmpZipcodeExample example);
}