-- User: ais
-- DROP USER ais;

CREATE USER ais WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  VALID UNTIL '2020-12-31 22:23:48+09'

GRANT postgres TO ais WITH ADMIN OPTION;

COMMENT ON ROLE ais IS 'AISŽÐ“à‹³ˆç—p';